import { describe, it, expect } from 'vitest';
import { emitWidgetTest } from '../../src/compiler/test-emitter';
import { IRDocument } from '../../src/ir/schema';
import componentInstanceFixture from '../fixtures/component-instance.ir.json';
import autoLayoutColumnFixture from '../fixtures/auto-layout-column.ir.json';
import screenshotGoldenFixture from '../fixtures/screenshot-golden.ir.json';

describe('TestEmitter', () => {
  describe('component test generation', () => {
    it('generates golden test for a component', () => {
      const ir = componentInstanceFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/primary_button.dart',
        componentName: 'PrimaryButton',
      });

      expect(result).toContain("import 'package:alchemist/alchemist.dart';");
      expect(result).toContain("import 'package:app/widgets/primary_button.dart';");
      expect(result).toContain("group('PrimaryButton'");
      expect(result).toContain("goldenTest(");
      expect(result).toContain("fileName: 'primary_button'");
      expect(result).toContain("child: PrimaryButton()");
    });

    it('generates text content assertions', () => {
      const ir = componentInstanceFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/primary_button.dart',
        componentName: 'PrimaryButton',
      });

      expect(result).toContain("expect(find.text('Get Started'), findsOneWidget);");
    });
  });

  describe('frame with nested text', () => {
    it('finds all text nodes in nested structure', () => {
      const ir = autoLayoutColumnFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/card_content.dart',
      });

      expect(result).toContain("expect(find.text('Restaurant Name'), findsOneWidget);");
      expect(result).toContain("find.text('渋谷区 • イタリアン')");
    });

    it('auto-derives class name from IR metadata', () => {
      const ir = autoLayoutColumnFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/card.dart',
      });

      // figmaNodeName is "Card Content" → PascalCase "CardContent"
      expect(result).toContain("group('CardContent'");
    });
  });

  describe('test structure', () => {
    it('generates valid Dart test file structure', () => {
      const ir = componentInstanceFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/primary_button.dart',
        componentName: 'PrimaryButton',
      });

      expect(result).toContain('void main() {');
      expect(result).toContain("testWidgets('matches Figma design specifications'");
      expect(result).toContain('await tester.pumpWidget(');
      expect(result).toContain('// GENERATED by figma2flutter');
    });

    it('includes token import when provided', () => {
      const ir = componentInstanceFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/primary_button.dart',
        tokenImport: 'package:app/tokens/app_colors.dart',
        componentName: 'PrimaryButton',
      });

      expect(result).toContain("import 'package:app/tokens/app_colors.dart';");
    });
  });

  describe('screenshot golden test', () => {
    it('generates screenshot comparison test when screenshots present', () => {
      const ir = screenshotGoldenFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/screenshot_card.dart',
        componentName: 'ScreenshotCard',
      });

      expect(result).toContain("'matches Figma reference screenshot'");
      expect(result).toContain('RepaintBoundary(');
      expect(result).toContain('matchesGoldenFile(');
      expect(result).toContain("goldens/screenshot_card.png");
      expect(result).toContain('width: 200,');
      expect(result).toContain('height: 100,');
    });

    it('does not generate screenshot test when screenshots absent', () => {
      const ir = componentInstanceFixture as unknown as IRDocument;
      const result = emitWidgetTest(ir, {
        widgetImport: 'package:app/widgets/primary_button.dart',
        componentName: 'PrimaryButton',
      });

      expect(result).not.toContain('matchesGoldenFile');
      expect(result).not.toContain('RepaintBoundary');
    });
  });
});
