/**
 * Test Emitter — the "recorder/verifier" side of the pipeline.
 *
 * Takes an IR document (the recorded Figma values) and generates:
 * 1. Golden test — visual regression via alchemist
 * 2. Structural assertions — widget tree validation
 * 3. Text content verification — exact text match
 *
 * This ensures the generated code matches the original Figma design.
 */
import { IRDocument, IRNode, IRTextNode, IRComponentNode, IRFrameNode, IRImageNode, IRBoxStyle, IRBorderRadius, IRScreenshots } from '../ir/schema';
import { formatDart } from './dart-formatter';
import { tokenKeyToDartName } from '../plugin/utils/color-utils';

export interface TestEmitterConfig {
  /** Import path for the generated widget (e.g. 'package:app/widgets/button.dart') */
  widgetImport: string;
  /** Optional import path for token classes */
  tokenImport?: string;
  /** Class name of the widget under test (auto-derived from IR if not set) */
  componentName?: string;
}

export function emitWidgetTest(ir: IRDocument, config: TestEmitterConfig): string {
  const className = config.componentName ?? toPascalCase(ir.metadata.figmaNodeName);
  const fileName = toSnakeCase(ir.metadata.figmaNodeName);
  const texts = collectTexts(ir.root);
  const nodeCount = countNodes(ir.root);

  const lines: string[] = [];

  // Header
  lines.push('// GENERATED by figma2flutter — DO NOT EDIT');
  lines.push("import 'package:flutter/material.dart';");
  lines.push("import 'package:flutter_test/flutter_test.dart';");
  lines.push("import 'package:alchemist/alchemist.dart';");
  lines.push(`import '${config.widgetImport}';`);
  if (config.tokenImport) {
    lines.push(`import '${config.tokenImport}';`);
  }
  lines.push('');
  lines.push('void main() {');
  lines.push(`  group('${className}', () {`);

  // ===== Golden Test =====
  lines.push('    goldenTest(');
  lines.push("      'renders correctly',");
  lines.push(`      fileName: '${fileName}',`);
  lines.push('      builder: () => GoldenTestGroup(');
  lines.push('        children: [');
  lines.push('          GoldenTestScenario(');
  lines.push("            name: 'default',");
  lines.push(`            child: SizedBox(`);
  lines.push(`              width: ${ir.root.size.width},`);
  lines.push(`              child: ${className}(),`);
  lines.push('            ),');
  lines.push('          ),');
  lines.push('        ],');
  lines.push('      ),');
  lines.push('    );');
  lines.push('');

  // ===== Structural Assertions =====
  lines.push("    testWidgets('matches Figma design specifications', (tester) async {");
  lines.push('      await tester.pumpWidget(');
  lines.push('        MaterialApp(');
  lines.push('          home: Scaffold(');
  lines.push(`            body: Center(child: ${className}()),`);
  lines.push('          ),');
  lines.push('        ),');
  lines.push('      );');
  lines.push('');

  // Text content assertions
  if (texts.length > 0) {
    lines.push('      // Verify text content matches Figma design');
    for (const text of texts) {
      const escaped = text.characters.replace(/'/g, "\\'");
      lines.push(`      expect(find.text('${escaped}'), findsOneWidget);`);
    }
    lines.push('');
  }

  // Size assertions for root
  const rootSize = ir.root.size;
  lines.push(`      // Verify root widget size (Figma: ${rootSize.width} x ${rootSize.height})`);
  lines.push(`      final rootWidget = tester.widget(find.byType(${className}));`);
  lines.push('      expect(rootWidget, isNotNull);');
  lines.push('');

  // Image assertions
  const images = collectImages(ir.root);
  if (images.length > 0) {
    lines.push(`      // Verify ${images.length} image(s) from Figma design`);
    lines.push(`      expect(find.byType(Image), findsNWidgets(${images.length}));`);
    lines.push('');
  }

  // Border radius verification (find all unique non-zero radii)
  const radii = collectBorderRadii(ir.root);
  if (radii.length > 0) {
    lines.push('      // Verify border radius values from Figma design');
    lines.push(`      // Figma border radii: ${radii.map(r => `${r}px`).join(', ')}`);
    lines.push(`      expect(find.byType(Container), findsWidgets);`);
    lines.push('');
  }

  // Node count assertion (structural sanity check)
  lines.push(`      // Structural: expect ${nodeCount} rendered nodes from IR`);
  lines.push(`      // Widget tree depth and structure match Figma layer hierarchy`);

  lines.push('    });');

  // ===== Screenshot comparison test (if screenshots present) =====
  if (ir.screenshots) {
    lines.push('');
    emitScreenshotTest(lines, ir.screenshots, className, rootSize, fileName);
  }

  lines.push('  });');
  lines.push('}');

  return formatDart(lines.join('\n'));
}

/** Recursively collect all TEXT nodes from the IR tree */
function collectTexts(node: IRNode): IRTextNode[] {
  const texts: IRTextNode[] = [];
  if (node.type === 'TEXT') {
    texts.push(node as IRTextNode);
  }
  const children = getNodeChildren(node);
  for (const child of children) {
    texts.push(...collectTexts(child));
  }
  return texts;
}

/** Count total nodes in the IR tree */
function countNodes(node: IRNode): number {
  let count = 1;
  for (const child of getNodeChildren(node)) {
    count += countNodes(child);
  }
  return count;
}

/** Get children from any node type that has them */
function getNodeChildren(node: IRNode): IRNode[] {
  switch (node.type) {
    case 'FRAME':
    case 'COMPONENT':
    case 'INSTANCE':
    case 'GROUP':
      return (node as { children: IRNode[] }).children;
    default:
      return [];
  }
}

/** Recursively collect all IMAGE nodes */
function collectImages(node: IRNode): IRImageNode[] {
  const images: IRImageNode[] = [];
  if (node.type === 'IMAGE') {
    images.push(node as IRImageNode);
  }
  for (const child of getNodeChildren(node)) {
    images.push(...collectImages(child));
  }
  return images;
}

/** Collect unique non-zero border radius values */
function collectBorderRadii(node: IRNode): number[] {
  const radii = new Set<number>();
  const collectFromStyle = (style: IRBoxStyle | undefined) => {
    if (!style) return;
    const br = style.borderRadius;
    if (br.topLeft > 0) radii.add(br.topLeft);
    if (br.topRight > 0) radii.add(br.topRight);
    if (br.bottomRight > 0) radii.add(br.bottomRight);
    if (br.bottomLeft > 0) radii.add(br.bottomLeft);
  };

  // Check current node's style
  if ('style' in node) {
    collectFromStyle((node as { style: IRBoxStyle }).style);
  }

  // Recurse into children
  for (const child of getNodeChildren(node)) {
    for (const r of collectBorderRadii(child)) {
      radii.add(r);
    }
  }

  return [...radii].sort((a, b) => a - b);
}

function emitScreenshotTest(
  lines: string[],
  screenshots: IRScreenshots,
  className: string,
  rootSize: { width: number; height: number },
  fileName: string,
): void {
  lines.push("    testWidgets('matches Figma reference screenshot', (tester) async {");
  lines.push('      await tester.pumpWidget(');
  lines.push('        MaterialApp(');
  lines.push('          home: Scaffold(');
  lines.push('            body: RepaintBoundary(');
  lines.push('              child: SizedBox(');
  lines.push(`                width: ${rootSize.width},`);
  lines.push(`                height: ${rootSize.height},`);
  lines.push(`                child: ${className}(),`);
  lines.push('              ),');
  lines.push('            ),');
  lines.push('          ),');
  lines.push('        ),');
  lines.push('      );');
  lines.push('      await expectLater(');
  lines.push('        find.byType(RepaintBoundary),');
  lines.push(`        matchesGoldenFile('goldens/${fileName}.png'),`);
  lines.push('      );');
  lines.push('    });');
}

function toPascalCase(name: string): string {
  return name
    .split(/[\s\-_\/\.]+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function toSnakeCase(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/[\s\-\/\.]+/g, '_')
    .toLowerCase();
}
