export const IR_VERSION = '1.0.0' as const;
export const PLUGIN_VERSION = '0.1.0';
export const GENERATED_HEADER = '// GENERATED by figma2flutter — DO NOT EDIT';
export const INDENT = '  '; // 2 spaces for Dart
